package pubmedstruct

///////////////////////////
/// structs: generated by chidley https://github.com/gnewton/chidley
/// that is why all structs start with ""
///////////////////////////

type root struct {
	PubmedArticleSet *PubmedArticleSet `xml:" PubmedArticleSet,omitempty" json:"PubmedArticleSet,omitempty"`
}

type PubmedArticleSet struct {
	PubmedArticle     []*PubmedArticle     `xml:" PubmedArticle,omitempty" json:"PubmedArticle,omitempty"`
	PubmedBookArticle []*PubmedBookArticle `xml:" PubmedBookArticle,omitempty" json:"PubmedBookArticle,omitempty"`
}

type PubmedBookArticle struct {
	BookDocument   *BookDocument   `xml:" BookDocument,omitempty" json:"BookDocument,omitempty"`
	PubmedBookData *PubmedBookData `xml:" PubmedBookData,omitempty" json:"PubmedBookData,omitempty"`
}

type BookDocument struct {
	Abstract         *Abstract          `xml:" Abstract,omitempty" json:"Abstract,omitempty"`
	ArticleIdList    *ArticleIdList     `xml:" ArticleIdList,omitempty" json:"ArticleIdList,omitempty"`
	ArticleTitle     *ArticleTitle      `xml:" ArticleTitle,omitempty" json:"ArticleTitle,omitempty"`
	AuthorList       *AuthorList        `xml:" AuthorList,omitempty" json:"AuthorList,omitempty"`
	Book             *Book              `xml:" Book,omitempty" json:"Book,omitempty"`
	ContributionDate *ContributionDate  `xml:" ContributionDate,omitempty" json:"ContributionDate,omitempty"`
	ItemList         *ItemList          `xml:" ItemList,omitempty" json:"ItemList,omitempty"`
	KeywordList      *KeywordList       `xml:" KeywordList,omitempty" json:"KeywordList,omitempty"`
	Language         []*Language        `xml:" Language,omitempty" json:"Language,omitempty"`
	LocationLabel    *LocationLabel     `xml:" LocationLabel,omitempty" json:"LocationLabel,omitempty"`
	PMID             *PMID              `xml:" PMID,omitempty" json:"PMID,omitempty"`
	PublicationType  []*PublicationType `xml:" PublicationType,omitempty" json:"PublicationType,omitempty"`
	Sections         *Sections          `xml:" Sections,omitempty" json:"Sections,omitempty"`
}

type AuthorList struct {
	Attr_CompleteYN string    `xml:" CompleteYN,attr"  json:",omitempty"`
	Attr_Type       string    `xml:" Type,attr"  json:",omitempty"`
	Author          []*Author `xml:" Author,omitempty" json:"Author,omitempty"`
}

type Author struct {
	Attr_ValidYN   string          `xml:" ValidYN,attr"  json:",omitempty"`
	Affiliation    *Affiliation    `xml:" Affiliation,omitempty" json:"Affiliation,omitempty"`
	CollectiveName *CollectiveName `xml:" CollectiveName,omitempty" json:"CollectiveName,omitempty"`
	ForeName       *ForeName       `xml:" ForeName,omitempty" json:"ForeName,omitempty"`
	Identifier     *Identifier     `xml:" Identifier,omitempty" json:"Identifier,omitempty"`
	Initials       *Initials       `xml:" Initials,omitempty" json:"Initials,omitempty"`
	LastName       *LastName       `xml:" LastName,omitempty" json:"LastName,omitempty"`
	Suffix         *Suffix         `xml:" Suffix,omitempty" json:"Suffix,omitempty"`
}

type Affiliation struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Identifier struct {
	Attr_Source string `xml:" Source,attr"  json:",omitempty"`
	Text        string `xml:",chardata" json:",omitempty"`
}

type CollectiveName struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Suffix struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type LastName struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type ForeName struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Initials struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type KeywordList struct {
	Attr_Owner string     `xml:" Owner,attr"  json:",omitempty"`
	Keyword    []*Keyword `xml:" Keyword,omitempty" json:"Keyword,omitempty"`
}

type Keyword struct {
	Attr_MajorTopicYN string `xml:" MajorTopicYN,attr"  json:",omitempty"`
	Text              string `xml:",chardata" json:",omitempty"`
}

type LocationLabel struct {
	Attr_Type string `xml:" Type,attr"  json:",omitempty"`
	Text      string `xml:",chardata" json:",omitempty"`
}

type ItemList struct {
	Attr_ListType string `xml:" ListType,attr"  json:",omitempty"`
	Item          *Item  `xml:" Item,omitempty" json:"Item,omitempty"`
}

type Item struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Abstract struct {
	AbstractText         []*AbstractText       `xml:" AbstractText,omitempty" json:"AbstractText,omitempty"`
	CopyrightInformation *CopyrightInformation `xml:" CopyrightInformation,omitempty" json:"CopyrightInformation,omitempty"`
}

type CopyrightInformation struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type AbstractText struct {
	Attr_Label       string `xml:" Label,attr"  json:",omitempty"`
	Attr_NlmCategory string `xml:" NlmCategory,attr"  json:",omitempty"`
	Text             string `xml:",chardata" json:",omitempty"`
}

type Sections struct {
	Section []*Section `xml:" Section,omitempty" json:"Section,omitempty"`
}

type Section struct {
	LocationLabel *LocationLabel `xml:" LocationLabel,omitempty" json:"LocationLabel,omitempty"`
	SectionTitle  *SectionTitle  `xml:" SectionTitle,omitempty" json:"SectionTitle,omitempty"`
}

type SectionTitle struct {
	Attr_book string `xml:" book,attr"  json:",omitempty"`
	Attr_part string `xml:" part,attr"  json:",omitempty"`
	Attr_sec  string `xml:" sec,attr"  json:",omitempty"`
	Text      string `xml:",chardata" json:",omitempty"`
}

type ArticleTitle struct {
	Attr_book string `xml:" book,attr"  json:",omitempty"`
	Attr_part string `xml:" part,attr"  json:",omitempty"`
	Text      string `xml:",chardata" json:",omitempty"`
}

type Language struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type PublicationType struct {
	Attr_UI string `xml:" UI,attr"  json:",omitempty"`
	Text    string `xml:",chardata" json:",omitempty"`
}

type ContributionDate struct {
	Day   *Day   `xml:" Day,omitempty" json:"Day,omitempty"`
	Month *Month `xml:" Month,omitempty" json:"Month,omitempty"`
	Year  *Year  `xml:" Year,omitempty" json:"Year,omitempty"`
}

type Year struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Month struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Day struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type PMID struct {
	Attr_Version string `xml:" Version,attr"  json:",omitempty"`
	Text         string `xml:",chardata" json:",omitempty"`
}

type ArticleIdList struct {
	ArticleId []*ArticleId `xml:" ArticleId,omitempty" json:"ArticleId,omitempty"`
}

type ArticleId struct {
	Attr_IdType string `xml:" IdType,attr"  json:",omitempty"`
	Text        string `xml:",chardata" json:",omitempty"`
}

type Book struct {
	AuthorList      *AuthorList      `xml:" AuthorList,omitempty" json:"AuthorList,omitempty"`
	BeginningDate   *BeginningDate   `xml:" BeginningDate,omitempty" json:"BeginningDate,omitempty"`
	BookTitle       *BookTitle       `xml:" BookTitle,omitempty" json:"BookTitle,omitempty"`
	CollectionTitle *CollectionTitle `xml:" CollectionTitle,omitempty" json:"CollectionTitle,omitempty"`
	ELocationID     []*ELocationID   `xml:" ELocationID,omitempty" json:"ELocationID,omitempty"`
	Edition         *Edition         `xml:" Edition,omitempty" json:"Edition,omitempty"`
	EndingDate      *EndingDate      `xml:" EndingDate,omitempty" json:"EndingDate,omitempty"`
	Isbn            *Isbn            `xml:" Isbn,omitempty" json:"Isbn,omitempty"`
	Medium          *Medium          `xml:" Medium,omitempty" json:"Medium,omitempty"`
	PubDate         *PubDate         `xml:" PubDate,omitempty" json:"PubDate,omitempty"`
	Publisher       *Publisher       `xml:" Publisher,omitempty" json:"Publisher,omitempty"`
	ReportNumber    *ReportNumber    `xml:" ReportNumber,omitempty" json:"ReportNumber,omitempty"`
}

type CollectionTitle struct {
	Attr_book string `xml:" book,attr"  json:",omitempty"`
	Text      string `xml:",chardata" json:",omitempty"`
}

type ELocationID struct {
	Attr_EIdType string `xml:" EIdType,attr"  json:",omitempty"`
	Attr_ValidYN string `xml:" ValidYN,attr"  json:",omitempty"`
	Text         string `xml:",chardata" json:",omitempty"`
}

type Medium struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Isbn struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type BookTitle struct {
	Attr_book string `xml:" book,attr"  json:",omitempty"`
	Text      string `xml:",chardata" json:",omitempty"`
}

type PubDate struct {
	Day         *Day         `xml:" Day,omitempty" json:"Day,omitempty"`
	MedlineDate *MedlineDate `xml:" MedlineDate,omitempty" json:"MedlineDate,omitempty"`
	Month       *Month       `xml:" Month,omitempty" json:"Month,omitempty"`
	Season      *Season      `xml:" Season,omitempty" json:"Season,omitempty"`
	Year        *Year        `xml:" Year,omitempty" json:"Year,omitempty"`
}

type MedlineDate struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Season struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type BeginningDate struct {
	Month *Month `xml:" Month,omitempty" json:"Month,omitempty"`
	Year  *Year  `xml:" Year,omitempty" json:"Year,omitempty"`
}

type EndingDate struct {
	Year *Year `xml:" Year,omitempty" json:"Year,omitempty"`
}

type Edition struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type ReportNumber struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Publisher struct {
	PublisherLocation *PublisherLocation `xml:" PublisherLocation,omitempty" json:"PublisherLocation,omitempty"`
	PublisherName     *PublisherName     `xml:" PublisherName,omitempty" json:"PublisherName,omitempty"`
}

type PublisherName struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type PublisherLocation struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type PubmedBookData struct {
	ArticleIdList     *ArticleIdList     `xml:" ArticleIdList,omitempty" json:"ArticleIdList,omitempty"`
	History           *History           `xml:" History,omitempty" json:"History,omitempty"`
	PublicationStatus *PublicationStatus `xml:" PublicationStatus,omitempty" json:"PublicationStatus,omitempty"`
}

type History struct {
	PubMedPubDate []*PubMedPubDate `xml:" PubMedPubDate,omitempty" json:"PubMedPubDate,omitempty"`
}

type PubMedPubDate struct {
	Attr_PubStatus string  `xml:" PubStatus,attr"  json:",omitempty"`
	Day            *Day    `xml:" Day,omitempty" json:"Day,omitempty"`
	Hour           *Hour   `xml:" Hour,omitempty" json:"Hour,omitempty"`
	Minute         *Minute `xml:" Minute,omitempty" json:"Minute,omitempty"`
	Month          *Month  `xml:" Month,omitempty" json:"Month,omitempty"`
	Year           *Year   `xml:" Year,omitempty" json:"Year,omitempty"`
}

type Hour struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Minute struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type PublicationStatus struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type PubmedArticle struct {
	MedlineCitation *MedlineCitation `xml:" MedlineCitation,omitempty" json:"MedlineCitation,omitempty"`
	PubmedData      *PubmedData      `xml:" PubmedData,omitempty" json:"PubmedData,omitempty"`
}

type MedlineCitation struct {
	Attr_Status             string                   `xml:" Status,attr"  json:",omitempty"`
	Attr_Owner              string                   `xml:" Owner,attr"  json:",omitempty"`
	Attr_VersionDate        string                   `xml:" VersionDate,attr"  json:",omitempty"`
	Attr_VersionID          string                   `xml:" VersionID,attr"  json:",omitempty"`
	Article                 *Article                 `xml:" Article,omitempty" json:"Article,omitempty"`
	ChemicalList            *ChemicalList            `xml:" ChemicalList,omitempty" json:"ChemicalList,omitempty"`
	CitationSubset          []*CitationSubset        `xml:" CitationSubset,omitempty" json:"CitationSubset,omitempty"`
	CommentsCorrectionsList *CommentsCorrectionsList `xml:" CommentsCorrectionsList,omitempty" json:"CommentsCorrectionsList,omitempty"`
	DateCompleted           *DateCompleted           `xml:" DateCompleted,omitempty" json:"DateCompleted,omitempty"`
	DateCreated             *DateCreated             `xml:" DateCreated,omitempty" json:"DateCreated,omitempty"`
	DateRevised             *DateRevised             `xml:" DateRevised,omitempty" json:"DateRevised,omitempty"`
	GeneralNote             *GeneralNote             `xml:" GeneralNote,omitempty" json:"GeneralNote,omitempty"`
	InvestigatorList        *InvestigatorList        `xml:" InvestigatorList,omitempty" json:"InvestigatorList,omitempty"`
	KeywordList             *KeywordList             `xml:" KeywordList,omitempty" json:"KeywordList,omitempty"`
	MedlineJournalInfo      *MedlineJournalInfo      `xml:" MedlineJournalInfo,omitempty" json:"MedlineJournalInfo,omitempty"`
	MeshHeadingList         *MeshHeadingList         `xml:" MeshHeadingList,omitempty" json:"MeshHeadingList,omitempty"`
	OtherAbstract           []*OtherAbstract         `xml:" OtherAbstract,omitempty" json:"OtherAbstract,omitempty"`
	OtherID                 []*OtherID               `xml:" OtherID,omitempty" json:"OtherID,omitempty"`
	PMID                    *PMID                    `xml:" PMID,omitempty" json:"PMID,omitempty"`
	PersonalNameSubjectList *PersonalNameSubjectList `xml:" PersonalNameSubjectList,omitempty" json:"PersonalNameSubjectList,omitempty"`
}

type DateRevised struct {
	Day   *Day   `xml:" Day,omitempty" json:"Day,omitempty"`
	Month *Month `xml:" Month,omitempty" json:"Month,omitempty"`
	Year  *Year  `xml:" Year,omitempty" json:"Year,omitempty"`
}

type CitationSubset struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type InvestigatorList struct {
	Investigator []*Investigator `xml:" Investigator,omitempty" json:"Investigator,omitempty"`
}

type Investigator struct {
	Attr_ValidYN string       `xml:" ValidYN,attr"  json:",omitempty"`
	Affiliation  *Affiliation `xml:" Affiliation,omitempty" json:"AffiliationInfo,omitempty"`
	ForeName     *ForeName    `xml:" ForeName,omitempty" json:"ForeName,omitempty"`
	Initials     *Initials    `xml:" Initials,omitempty" json:"Initials,omitempty"`
	LastName     *LastName    `xml:" LastName,omitempty" json:"LastName,omitempty"`
	Suffix       *Suffix      `xml:" Suffix,omitempty" json:"Suffix,omitempty"`
}

type OtherAbstract struct {
	Attr_Language string          `xml:" Language,attr"  json:",omitempty"`
	Attr_Type     string          `xml:" Type,attr"  json:",omitempty"`
	AbstractText  []*AbstractText `xml:" AbstractText,omitempty" json:"AbstractText,omitempty"`
}

type DateCompleted struct {
	Day   *Day   `xml:" Day,omitempty" json:"Day,omitempty"`
	Month *Month `xml:" Month,omitempty" json:"Month,omitempty"`
	Year  *Year  `xml:" Year,omitempty" json:"Year,omitempty"`
}

type MeshHeadingList struct {
	MeshHeading []*MeshHeading `xml:" MeshHeading,omitempty" json:"MeshHeading,omitempty"`
}

type MeshHeading struct {
	DescriptorName *DescriptorName  `xml:" DescriptorName,omitempty" json:"DescriptorName,omitempty"`
	QualifierName  []*QualifierName `xml:" QualifierName,omitempty" json:"QualifierName,omitempty"`
}

type DescriptorName struct {
	Attr_MajorTopicYN string `xml:" MajorTopicYN,attr"  json:",omitempty"`
	Attr_UI           string `xml:" UI,attr"  json:",omitempty"`
	Attr_Type         string `xml:" Type,attr"  json:",omitempty"`
	Text              string `xml:",chardata" json:",omitempty"`
}

type QualifierName struct {
	Attr_MajorTopicYN string `xml:" MajorTopicYN,attr"  json:",omitempty"`
	Attr_UI           string `xml:" UI,attr"  json:",omitempty"`
	Text              string `xml:",chardata" json:",omitempty"`
}

type GeneralNote struct {
	Attr_Owner string `xml:" Owner,attr"  json:",omitempty"`
	Text       string `xml:",chardata" json:",omitempty"`
}

type DateCreated struct {
	Day   *Day   `xml:" Day,omitempty" json:"Day,omitempty"`
	Month *Month `xml:" Month,omitempty" json:"Month,omitempty"`
	Year  *Year  `xml:" Year,omitempty" json:"Year,omitempty"`
}

type Article struct {
	Attr_PubModel       string               `xml:" PubModel,attr"  json:",omitempty"`
	Abstract            *Abstract            `xml:" Abstract,omitempty" json:"Abstract,omitempty"`
	ArticleDate         *ArticleDate         `xml:" ArticleDate,omitempty" json:"ArticleDate,omitempty"`
	ArticleTitle        *ArticleTitle        `xml:" ArticleTitle,omitempty" json:"ArticleTitle,omitempty"`
	AuthorList          *AuthorList          `xml:" AuthorList,omitempty" json:"AuthorList,omitempty"`
	DataBankList        *DataBankList        `xml:" DataBankList,omitempty" json:"DataBankList,omitempty"`
	ELocationID         []*ELocationID       `xml:" ELocationID,omitempty" json:"ELocationID,omitempty"`
	GrantList           *GrantList           `xml:" GrantList,omitempty" json:"GrantList,omitempty"`
	Journal             *Journal             `xml:" Journal,omitempty" json:"Journal,omitempty"`
	Language            []*Language          `xml:" Language,omitempty" json:"Language,omitempty"`
	Pagination          *Pagination          `xml:" Pagination,omitempty" json:"Pagination,omitempty"`
	PublicationTypeList *PublicationTypeList `xml:" PublicationTypeList,omitempty" json:"PublicationTypeList,omitempty"`
	VernacularTitle     *VernacularTitle     `xml:" VernacularTitle,omitempty" json:"VernacularTitle,omitempty"`
}

type GrantList struct {
	Attr_CompleteYN string   `xml:" CompleteYN,attr"  json:",omitempty"`
	Grant           []*Grant `xml:" Grant,omitempty" json:"Grant,omitempty"`
}

type Grant struct {
	Acronym *Acronym `xml:" Acronym,omitempty" json:"Acronym,omitempty"`
	Agency  *Agency  `xml:" Agency,omitempty" json:"Agency,omitempty"`
	Country *Country `xml:" Country,omitempty" json:"Country,omitempty"`
	GrantID *GrantID `xml:" GrantID,omitempty" json:"GrantID,omitempty"`
}

type GrantID struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Acronym struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Agency struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Country struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type VernacularTitle struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Journal struct {
	ISOAbbreviation *ISOAbbreviation `xml:" ISOAbbreviation,omitempty" json:"ISOAbbreviation,omitempty"`
	ISSN            *ISSN            `xml:" ISSN,omitempty" json:"ISSN,omitempty"`
	JournalIssue    *JournalIssue    `xml:" JournalIssue,omitempty" json:"JournalIssue,omitempty"`
	Title           *Title           `xml:" Title,omitempty" json:"Title,omitempty"`
}

type ISSN struct {
	Attr_IssnType string `xml:" IssnType,attr"  json:",omitempty"`
	Text          string `xml:",chardata" json:",omitempty"`
}

type JournalIssue struct {
	Attr_CitedMedium string   `xml:" CitedMedium,attr"  json:",omitempty"`
	Issue            *Issue   `xml:" Issue,omitempty" json:"Issue,omitempty"`
	PubDate          *PubDate `xml:" PubDate,omitempty" json:"PubDate,omitempty"`
	Volume           *Volume  `xml:" Volume,omitempty" json:"Volume,omitempty"`
}

type Volume struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Issue struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Title struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type ISOAbbreviation struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type PublicationTypeList struct {
	PublicationType []*PublicationType `xml:" PublicationType,omitempty" json:"PublicationType,omitempty"`
}

type ArticleDate struct {
	Attr_DateType string `xml:" DateType,attr"  json:",omitempty"`
	Day           *Day   `xml:" Day,omitempty" json:"Day,omitempty"`
	Month         *Month `xml:" Month,omitempty" json:"Month,omitempty"`
	Year          *Year  `xml:" Year,omitempty" json:"Year,omitempty"`
}

type DataBankList struct {
	Attr_CompleteYN string      `xml:" CompleteYN,attr"  json:",omitempty"`
	DataBank        []*DataBank `xml:" DataBank,omitempty" json:"DataBank,omitempty"`
}

type DataBank struct {
	AccessionNumberList *AccessionNumberList `xml:" AccessionNumberList,omitempty" json:"AccessionNumberList,omitempty"`
	DataBankName        *DataBankName        `xml:" DataBankName,omitempty" json:"DataBankName,omitempty"`
}

type DataBankName struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type AccessionNumberList struct {
	AccessionNumber []*AccessionNumber `xml:" AccessionNumber,omitempty" json:"AccessionNumber,omitempty"`
}

type AccessionNumber struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Pagination struct {
	MedlinePgn *MedlinePgn `xml:" MedlinePgn,omitempty" json:"MedlinePgn,omitempty"`
}

type MedlinePgn struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type CommentsCorrectionsList struct {
	CommentsCorrections []*CommentsCorrections `xml:" CommentsCorrections,omitempty" json:"CommentsCorrections,omitempty"`
}

type CommentsCorrections struct {
	Attr_RefType string     `xml:" RefType,attr"  json:",omitempty"`
	Note         *Note      `xml:" Note,omitempty" json:"Note,omitempty"`
	PMID         *PMID      `xml:" PMID,omitempty" json:"PMID,omitempty"`
	RefSource    *RefSource `xml:" RefSource,omitempty" json:"RefSource,omitempty"`
}

type RefSource struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type Note struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type OtherID struct {
	Attr_Source string `xml:" Source,attr"  json:",omitempty"`
	Text        string `xml:",chardata" json:",omitempty"`
}

type MedlineJournalInfo struct {
	Country     *Country     `xml:" Country,omitempty" json:"Country,omitempty"`
	ISSNLinking *ISSNLinking `xml:" ISSNLinking,omitempty" json:"ISSNLinking,omitempty"`
	MedlineTA   *MedlineTA   `xml:" MedlineTA,omitempty" json:"MedlineTA,omitempty"`
	NlmUniqueID *NlmUniqueID `xml:" NlmUniqueID,omitempty" json:"NlmUniqueID,omitempty"`
}

type MedlineTA struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type NlmUniqueID struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type ISSNLinking struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type ChemicalList struct {
	Chemical []*Chemical `xml:" Chemical,omitempty" json:"Chemical,omitempty"`
}

type Chemical struct {
	NameOfSubstance *NameOfSubstance `xml:" NameOfSubstance,omitempty" json:"NameOfSubstance,omitempty"`
	RegistryNumber  *RegistryNumber  `xml:" RegistryNumber,omitempty" json:"RegistryNumber,omitempty"`
}

type RegistryNumber struct {
	Text string `xml:",chardata" json:",omitempty"`
}

type NameOfSubstance struct {
	Attr_UI string `xml:" UI,attr"  json:",omitempty"`
	Text    string `xml:",chardata" json:",omitempty"`
}

type PersonalNameSubjectList struct {
	PersonalNameSubject *PersonalNameSubject `xml:" PersonalNameSubject,omitempty" json:"PersonalNameSubject,omitempty"`
}

type PersonalNameSubject struct {
	ForeName *ForeName `xml:" ForeName,omitempty" json:"ForeName,omitempty"`
	Initials *Initials `xml:" Initials,omitempty" json:"Initials,omitempty"`
	LastName *LastName `xml:" LastName,omitempty" json:"LastName,omitempty"`
}

type PubmedData struct {
	ArticleIdList     *ArticleIdList     `xml:" ArticleIdList,omitempty" json:"ArticleIdList,omitempty"`
	History           *History           `xml:" History,omitempty" json:"History,omitempty"`
	PublicationStatus *PublicationStatus `xml:" PublicationStatus,omitempty" json:"PublicationStatus,omitempty"`
}
